language: node_js
node_js:
  - 6
  - 5
  - 4
script:
  make test
cache:
  directories:
    - node_modules

after_success: npm i coveralls && $(npm bin)/nyc report --reporter=text-lcov | $(npm bin)/coveralls
